version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: green-postgres
    environment:
      POSTGRES_DB: green_energy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ml-api:
    build:
      context: .
      dockerfile: ml/api/Dockerfile
    container_name: ml-api
    ports:
      - "8000:8000"
    volumes:
      - ./ml/artifacts:/app/ml/artifacts

  generator-simulator:
    build:
      context: ./green-energy-platform
    container_name: generator-simulator
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - ml-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/green_energy
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      INTERSERVICE_ML_BASE_URL: http://ml-api:8000
    volumes:
      - ./data:/app/data

  backend:
    build:
      context: ./backend   # <-- если папка backend
    container_name: backend
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/green_energy
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  postgres_data:
