spring:
  application:
    name: generator-simulator
  spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

generator:
  startDate: 2023-01-01
  endDate: 2025-12-31
  generators: 50
  outputFile: data/historical/historical_events.jsonl

logging:
  level:
    root: INFO

interservice:
  ml:
    base-url: ${INTERSERVICE_ML_BASE_URL}
