spring:
  application:
    name: generator-simulator
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/green_energy
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

generator:
  startDate: 2023-01-01
  endDate: 2025-12-31
  generators: 50
  outputFile: data/historical/historical_events.jsonl

logging:
  level:
    root: INFO

interservice:
  ml:
    base-url: http://ml-api:8000
